### ISSUE TITLE
Error: Cannot find module 'metaweblog-api'

### ISSUE THREAD

**Issue by oliversturm** [uhavemyword/metaweblog-api#2]
This issue is probably the same as #1.

I found the cause of it -  `package.json` contains this:

```
"main": "./lib/metaWeblog-api.js",
```

However, the actual name of the file is `metaweblog-api.js` (no capital `W`). On systems where capitalization in file names matters (my system is Linux), this results in an error.

**Comment by uhavemyword** [comment]
thank you for pointing out the issue, it's been fixed.
